### ISSUE TITLE
receiver/source and input relationship

### ISSUE THREAD

**Issue by maxwalter79** [AMWA-TV/nmos-audio-channel-mapping#11]
In the "receiver/source and input relationship" section of "behaviour.md" document is described in which case the receivers parent object could be of type "source" and include its uuid as "parent id".

It seems to me like a big hurdle to get the "source uuid" peace of data to the receivers node.
The only information we have here is "sender_id" via IS-05 or a "subscription sender_id" via IS-04.
To gather the originating "source uuid" the receiver node should be capable of querying the registry or the sender node directly! Theoretically this would be possible but I'm not sure if this is worth the effort.

Do the "receiver node" really relies on this information (I don't think so), or is it more like a shortcut for the controller software?  If the latter one is true I would prefer to leave this task of resolving the parentage (sender -> flow -> source) to controller software itself.

**Comment by simonrankine** [comment]
Hi Max,

The reason this is there is to manage media that originates on the Device, rather than being received through an NMOS Receiver. You could easily imagine that you might have other APIs on the device carrying out other operations on the audio or generating audio, that provide a source ID in the same way as audio channel mapping to allow the their outputs to be identified. In this case the is no receiver ID, but we still need to be able to indicate to the control system what audio is coming into the Input.

Does that make sense?

**Comment by maxwalter79** [comment]
Hi Simon,

so in the case the audio stream is being received from other device, it would be ok to set the parent type of an input to a "receiver"?

**Comment by chris-gil** [comment]
If the channels presented to an input are from a receiver that information is required by the control system - the connectivity relationship between the receiver and input would be permanent I assume and the control system should always be able to determine the link.  

The input could report the id of the remote source that is connected like this:
"source->flow->sender->receiver->input" 

This would be a complex job for the device to calculate and could hide the receiver->input information from the control system.

**Comment by simonrankine** [comment]
Think this is all sorted, was covered again on the last call so will close for now.
