### ISSUE TITLE
[Docs] Examples from sub-directories not showing at amwa-tv.github.io

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-audio-channel-mapping#30]
https://amwa-tv.github.io/nmos-audio-channel-mapping/branches/v1.0.x/examples/ only shows:

* base-get-200
* io-get-200

whereas there are many more examples correctly embedded in the rendering of the RAML.

That's because the render scripts aren't looking for examples in sub-directories.

**Comment by peterbrightwell** [comment]
https://github.com/AMWA-TV/nmos-doc-build-scripts/commit/269b2341de69965519685f2023632e307d91d6b1 now renders subdirs of examples/.  It flattens them, so the output is similar to what is seen in the other repos (Gareth, I removed the `<dir>_`  prefix that you saw the other day). Haven't currently indented the subdirs because that would not match the other IS-xx renders.
