### ISSUE TITLE
IS-08 Specification suggestion

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos-audio-channel-mapping#38]
Next time it would be better to avoid page like IO, or INPUTS, OUTPUTS... These page can be very huge, since they list everything in one page. Small system with less memory will have a really hard time to populate those pages.

As an example, IS05 list the UUID, and using these UUID you can fetch the details of a specific IO/INPUT/OUTPUT.

This is a lot easier for all system, and even controller can fetch the data as per there datamodel.

I don't know if we can do something at this point... maybe in a v1.1 we could at least set a device maximum return per page.. or somehting similar...

**Comment by garethsb** [comment]
Pagination could be added to IS-08 Audio Channel Mapping API, following the pagination model used in IS-04 Query API (since v1.1) and IS-06 Network Control API.

This could be added in a v1.1 based on deployment experience.

**Comment by garethsb** [comment]
> Pagination could be added to IS-08 Audio Channel Mapping API, following the pagination model used in IS-04 Query API (since v1.1) and IS-06 Network Control API.

Actually it wouldn't be straightforward, at least in the case of the **/io** resource, since that is an object, not an array, and pagination cursors would be difficult to define. We'd probably need an alternative endpoint with a different design to enable pagination of the style used elsewhere.

On the other hand, the **/inputs** and **/outputs** resources only contain a string `id` for each input or output. Details of the individual input or output already requires a specific GET operation?

**Comment by peterbrightwell** [comment]
Architecture Review Group review: closing. Please use Incubator basecamp or #incubator / #nmos-community slack to propose an activity for inclusion in future version.
