### ISSUE TITLE
Clarification on sender side sequence diagram

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/nmos-audio-channel-mapping#62]
https://github.com/AMWA-TV/is-08/blob/v1.0.x/docs/images/sequence-diagrams/sender-sequence.png
In the above IS-08 sender-side sequence diagram, the fetch request resolves **ReceiverId** to **Input**,
it should be resolves **SendeId** to **Output** isn't it? or am I missing something here?

**Comment by garethsb** [comment]
I'm confused by the diagram as well... If you were correct, then it would be the **SenderId** that is already known, in which case the Controller would need to identify the associated Flow, and its associated Source, and use its **SourceId** to resolve the associated **Output** to be able to set up the channel map via IS-08.

But given the following interactions shown with the Query API, I don't think that's what is intended.

I _think_ the assumption in the diagram is that the User wants to start by changing the channel map (associated with a Receiver, but I agree I don't think that's right!) and then following the **Output** in the other direction than above... via its **SourceId** and then via the Query API to _a_ related Sender.

That doesn't make sense to me as a workflow.

@peterbrightwell, what are we missing? Let's discuss in @AMWA-TV/nmos-architecture-review team.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog

**Comment by garethsb** [comment]
ARG: simplest fix to make the diagram correct is to change like this...

```diff
< Fetch IO information and resolve the Receiver ID to an Input in the API, enumerate channels and discover permissible routing
----
> Fetch IO information and resolve the Source ID to an Output in the API, enumerate channels and discover permissible routing
```

The diagram then makes sense if the Client is starting from a specific Source ID.

Two more likely workflows seem to be:

1. the Client is first setting up the channel mapping for a specific Output, then arranging to transmit that via a Sender to a Receiver; in this case the Client resolves the Output to its Source ID, and then proceeds as in the diagram, discovering the associated Flow and then Sender, in order to have that Output transmitted to a Receiver
2. the Client is starts from a specific Sender, and before configuring it to transmit to a Receiver, discovers the associated Flow and then Source, before resolving the Source ID to an Output

Either of these would require slightly larger changes to the diagram.
